<%
	Set gobjConnection = Server.CreateObject("ADODB.Connection")
	gsConnect = "driver={MySQL ODBC 5.1 Driver}; database=slingsurvey2;server=localhost;uid=root;pwd=2100hbo7;port=3306;Option=16384;"
	gobjConnection.Open gsConnect
%>
<%
	'Each page must have a key string referenced or page will log out.
	KeyID = request.querystring("KeyID")
	
	if KeyID = "" then
		response.redirect("/survey/index.html?s=1")
	end if

	fielda = replace(request.form("fielda"), "'", "''")
	fieldb = replace(request.form("fieldb"), "'", "''")
	fieldc = replace(request.form("fieldc"), "'", "''")
	fieldd = replace(request.form("fieldd"), "'", "''")
	fielde = replace(request.form("fielde"), "'", "''")
	fieldf = replace(request.form("fieldf"), "'", "''")
	fieldf1 = replace(request.form("fieldf1"), "'", "''")
	fieldg = replace(request.form("fieldg"), "'", "''")
	fieldh = replace(request.form("fieldh"), "'", "''")
	fieldi = replace(request.form("fieldi"), "'", "''")
	fieldj = replace(request.form("fieldj"), "'", "''")
	fieldk = replace(request.form("fieldk"), "'", "''")
	fieldl = replace(request.form("fieldl"), "'", "''")
	fieldn = replace(request.form("fieldm"), "'", "''")
	fieldm = replace(request.form("fieldn"), "'", "''")
	fieldo = replace(request.form("fieldo"), "'", "''")
	fieldp = replace(request.form("fieldp"), "'", "''")
	fieldq = replace(request.form("fieldq"), "'", "''")	
	fieldq1 = replace(request.form("fieldq1"), "'", "''")	
	fieldr = replace(request.form("fieldr"), "'", "''")
	fieldt = replace(request.form("fieldt"), "'", "''")
	fieldu = replace(request.form("fieldu"), "'", "''")
		field1a = replace(request.form("field1a"), "'", "''")
		field1b = replace(request.form("field1b"), "'", "''")
		field1c = replace(request.form("field1c"), "'", "''")
		field1d = replace(request.form("field1d"), "'", "''")
		field1e = replace(request.form("field1e"), "'", "''")
		field1e1 = replace(request.form("field1e1"), "'", "''")
	field2a = replace(request.form("field2a"), "'", "''")
	field2b = replace(request.form("field2b"), "'", "''")
		field3a = replace(request.form("field3a"), "'", "''")
		field3b = replace(request.form("field3b"), "'", "''")
		field3b1 = replace(request.form("field3b1"), "'", "''")
		field3c = replace(request.form("field3c"), "'", "''")		
		field3c1 = replace(request.form("field3c1"), "'", "''")
		field3d = replace(request.form("field3d"), "'", "''")
		field3d1 = replace(request.form("field3d1"), "'", "''")
		field3d2 = replace(request.form("field3d2"), "'", "''")
		field3e = replace(request.form("field3e"), "'", "''")
	field4a = replace(request.form("field4a"), "'", "''")
	field4b = replace(request.form("field4b"), "'", "''")
	field4c = replace(request.form("field4c"), "'", "''")
	field4d = replace(request.form("field4d"), "'", "''")
	field4e = replace(request.form("field4e"), "'", "''")
		field5a = replace(request.form("field5a"), "'", "''")
		field5a1 = replace(request.form("field5a1"), "'", "''")
		field5a2 = replace(request.form("field5a2"), "'", "''")
		field5b = replace(request.form("field5b"), "'", "''")
		field5c = replace(request.form("field5c"), "'", "''")
	field6a = replace(request.form("field6a"), "'", "''")
	field6b = replace(request.form("field6b"), "'", "''")
	field6c = replace(request.form("field6c"), "'", "''")
		field7a = replace(request.form("field7a"), "'", "''")
		field7b = replace(request.form("field7b"), "'", "''")
		field7c = replace(request.form("field7c"), "'", "''")
	field8a = replace(request.form("field8a"), "'", "''")
	field8a1 = replace(request.form("field8a1"), "'", "''")
	field8a2 = replace(request.form("field8a2"), "'", "''")
	field8a3 = replace(request.form("field8a3"), "'", "''")
	field8a4 = replace(request.form("field8a4"), "'", "''")
	field8a5 = replace(request.form("field8a5"), "'", "''")
	field8a6 = replace(request.form("field8a6"), "'", "''")
	field8a7 = replace(request.form("field8a7"), "'", "''")
	field8a8 = replace(request.form("field8a8"), "'", "''")
	field8b = replace(request.form("field8b"), "'", "''")
	field8b1 = replace(request.form("field8b1"), "'", "''")
	field8b2 = replace(request.form("field8b2"), "'", "''")
	field8c = replace(request.form("field8c"), "'", "''")
	field8d = replace(request.form("field8d"), "'", "''")
		field9a = replace(request.form("field9a"), "'", "''")
		field9b = replace(request.form("field9b"), "'", "''")
		field9b1 = replace(request.form("field9b1"), "'", "''")
		field9b2 = replace(request.form("field9b2"), "'", "''")
		field9c = replace(request.form("field9c"), "'", "''")
		field9c1 = replace(request.form("field9c1"), "'", "''")
		field9c2 = replace(request.form("field9c2"), "'", "''")
		field9c3 = replace(request.form("field9c3"), "'", "''")
		field9c4 = replace(request.form("field9c4"), "'", "''")
		field9d = replace(request.form("field9d"), "'", "''")
		field9d1 = replace(request.form("field9d1"), "'", "''")
		field9d2 = replace(request.form("field9d2"), "'", "''")
		field9d3 = replace(request.form("field9d3"), "'", "''")
		field9d4 = replace(request.form("field9d4"), "'", "''")
		field9e = replace(request.form("field9e"), "'", "''")
		field9e1 = replace(request.form("field9e1"), "'", "''")
		field9e2 = replace(request.form("field9e2"), "'", "''")
		field9e3 = replace(request.form("field9e3"), "'", "''")
		field9f = replace(request.form("field9f"), "'", "''")
		field9f1 = replace(request.form("field9f1"), "'", "''")
		field9f2 = replace(request.form("field9f2"), "'", "''")
		field9f3 = replace(request.form("field9f3"), "'", "''")
		field9f4 = replace(request.form("field9f4"), "'", "''")
	field10a = replace(request.form("field10a"), "'", "''")
	field10b = replace(request.form("field10b"), "'", "''")
	field10c = replace(request.form("field10c"), "'", "''")
	field10d = replace(request.form("field10d"), "'", "''")
		field11a = replace(request.form("field11a"), "'", "''")
		field11a1 = replace(request.form("field11a1"), "'", "''")
		field11a2 = replace(request.form("field11a2"), "'", "''")
		field11b = replace(request.form("field11b"), "'", "''")
		field11c = replace(request.form("field11c"), "'", "''")
	field12a = replace(request.form("field12a"), "'", "''")
	field12b = replace(request.form("field12b"), "'", "''")
	field12c = replace(request.form("field12c"), "'", "''")
	field12d = replace(request.form("field12d"), "'", "''")
	field12e = replace(request.form("field12e"), "'", "''")
	field12f = replace(request.form("field12f"), "'", "''")
	field12g = replace(request.form("field12g"), "'", "''")
		field13a = replace(request.form("field13a"), "'", "''")
		field13b = replace(request.form("field13b"), "'", "''")
		field13c = replace(request.form("field13c"), "'", "''")
		field13d = replace(request.form("field13d"), "'", "''")
	field14a = replace(request.form("field14a"), "'", "''")
	field14b = replace(request.form("field14b"), "'", "''")
	field14c = replace(request.form("field14c"), "'", "''")
	field14d = replace(request.form("field14d"), "'", "''")
		field15a = replace(request.form("field15a"), "'", "''")
		field15b = replace(request.form("field15b"), "'", "''")
		field15c = replace(request.form("field15c"), "'", "''")
		field15d = replace(request.form("field15d"), "'", "''")
		field15e = replace(request.form("field15e"), "'", "''")
		field15f = replace(request.form("field15f"), "'", "''")
	field16a = replace(request.form("field16a"), "'", "''")
	field16b = replace(request.form("field16b"), "'", "''")
	field16c = replace(request.form("field16c"), "'", "''")
	field16d = replace(request.form("field16d"), "'", "''")
	field16e = replace(request.form("field16e"), "'", "''")
	field16f = replace(request.form("field16f"), "'", "''")
		field17a = replace(request.form("field17a"), "'", "''")
		field17b = replace(request.form("field17b"), "'", "''")
		field17c = replace(request.form("field17c"), "'", "''")
	field18a = replace(request.form("field18a"), "'", "''")
	field18b = replace(request.form("field18b"), "'", "''")
	field18c = replace(request.form("field18c"), "'", "''")
	field18d = replace(request.form("field18d"), "'", "''")
	field18e = replace(request.form("field18e"), "'", "''")
		field19a = replace(request.form("field19a"), "'", "''")
		field19b = replace(request.form("field19b"), "'", "''")
		field19c = replace(request.form("field19c"), "'", "''")
		field19d = replace(request.form("field19d"), "'", "''")
		field19d1 = replace(request.form("field19d1"), "'", "''")
		field19d2 = replace(request.form("field19d2"), "'", "''")
		field19d3 = replace(request.form("field19d3"), "'", "''")
		field19e = replace(request.form("field19e"), "'", "''")
	field20a = replace(request.form("field20a"), "'", "''")
	field20b = replace(request.form("field20b"), "'", "''")
	field20c = replace(request.form("field20c"), "'", "''")
	field20d = replace(request.form("field20d"), "'", "''")
	field20e = replace(request.form("field20e"), "'", "''")
	field20f = replace(request.form("field20f"), "'", "''")
	field20g = replace(request.form("field20g"), "'", "''")
		field21a = replace(request.form("field21a"), "'", "''")
		field21b = replace(request.form("field21b"), "'", "''")
	field22a = replace(request.form("field22a"), "'", "''")
	field22b = replace(request.form("field22b"), "'", "''")
		field23a = replace(request.form("field23a"), "'", "''")
		field23b = replace(request.form("field23b"), "'", "''")
	field24a = replace(request.form("field24a"), "'", "''")
	field24b = replace(request.form("field24b"), "'", "''")
	field24c = replace(request.form("field24c"), "'", "''")
		field25a = replace(request.form("field25a"), "'", "''")
		field25b = replace(request.form("field25b"), "'", "''")
		field25c = replace(request.form("field25c"), "'", "''")
	field26a = replace(request.form("field26a"), "'", "''")
	field26b = replace(request.form("field26b"), "'", "''")
	field26c = replace(request.form("field26c"), "'", "''")
	field26c1 = replace(request.form("field26c1"), "'", "''")
	field26d = replace(request.form("field26d"), "'", "''")
	field26d1 = replace(request.form("field26d1"), "'", "''")
	field26e = replace(request.form("field26e"), "'", "''")
		field27a = replace(request.form("field27a"), "'", "''")
		field27b = replace(request.form("field27b"), "'", "''")
		field27c = replace(request.form("field27c"), "'", "''")
	field28a = replace(request.form("field28a"), "'", "''")
	field28b = replace(request.form("field28b"), "'", "''")
	field28c = replace(request.form("field28c"), "'", "''")
		field29a = replace(request.form("field29a"), "'", "''")
		field29b = replace(request.form("field29b"), "'", "''")
		field29c = replace(request.form("field29c"), "'", "''")
		field29d = replace(request.form("field29d"), "'", "''")
	field30a = replace(request.form("field30a"), "'", "''")
	field30b = replace(request.form("field30b"), "'", "''")
	field30c = replace(request.form("field30c"), "'", "''")
	field30d = replace(request.form("field30d"), "'", "''")
	field30e = replace(request.form("field30e"), "'", "''")
	field30e1 = replace(request.form("field30e1"), "'", "''")
	field30e2 = replace(request.form("field30e2"), "'", "''")
	field30e3 = replace(request.form("field30e3"), "'", "''")
		field31a = replace(request.form("field31a"), "'", "''")
		field31b = replace(request.form("field31b"), "'", "''")
		field31c = replace(request.form("field31c"), "'", "''")
	field32a = replace(request.form("field32a"), "'", "''")
	field32b = replace(request.form("field32b"), "'", "''")
	field32c = replace(request.form("field32c"), "'", "''")
	field32d = replace(request.form("field32d"), "'", "''")
		field33a = replace(request.form("field33a"), "'", "''")
		field33b = replace(request.form("field33b"), "'", "''")
		field33c = replace(request.form("field33c"), "'", "''")
		field33d = replace(request.form("field33d"), "'", "''")
	field34a = replace(request.form("field34a"), "'", "''")
	field34b = replace(request.form("field34b"), "'", "''")
		field35a = replace(request.form("field35a"), "'", "''")
		field35b = replace(request.form("field35b"), "'", "''")
		field35c = replace(request.form("field35c"), "'", "''")
		field35d = replace(request.form("field35d"), "'", "''")
		field35e = replace(request.form("field35e"), "'", "''")
		field35f = replace(request.form("field35f"), "'", "''")
		field35f1 = replace(request.form("field35f1"), "'", "''")
		field35g = replace(request.form("field35g"), "'", "''")
		field35g1 = replace(request.form("field35g1"), "'", "''")
		field35h = replace(request.form("field35h"), "'", "''")
	field36a = replace(request.form("field36a"), "'", "''")
	field36b = replace(request.form("field36b"), "'", "''")
		field37a = replace(request.form("field37a"), "'", "''")
		field37b = replace(request.form("field37b"), "'", "''")
		field37c = replace(request.form("field37c"), "'", "''")
	field38a = replace(request.form("field38a"), "'", "''")
	field38b = replace(request.form("field38b"), "'", "''")
		field39a = replace(request.form("field39a"), "'", "''")
		field39b = replace(request.form("field39b"), "'", "''")
		field39c = replace(request.form("field39c"), "'", "''")
		field39d = replace(request.form("field39d"), "'", "''")
	field40a = replace(request.form("field40a"), "'", "''")
	field40b = replace(request.form("field40b"), "'", "''")
	field40c = replace(request.form("field40c"), "'", "''")
		field41a = replace(request.form("field41a"), "'", "''")
		field41b = replace(request.form("field41b"), "'", "''")
		field41c = replace(request.form("field41c"), "'", "''")
	field42a = replace(request.form("field42a"), "'", "''")
	field42b = replace(request.form("field42b"), "'", "''")
		field43a = replace(request.form("field43a"), "'", "''")
		field43b = replace(request.form("field43b"), "'", "''")
		field43c = replace(request.form("field43c"), "'", "''")
	field44a = replace(request.form("field44a"), "'", "''")
	field44b = replace(request.form("field44b"), "'", "''")
	field44c = replace(request.form("field44c"), "'", "''")
		field45a = replace(request.form("field45a"), "'", "''")
		field45b = replace(request.form("field45b"), "'", "''")
		field45c = replace(request.form("field45c"), "'", "''")
	field46a = replace(request.form("field46a"), "'", "''")
	field46b = replace(request.form("field46b"), "'", "''")
	field46c = replace(request.form("field46c"), "'", "''")
		field47a = replace(request.form("field47a"), "'", "''")
		field47b = replace(request.form("field47b"), "'", "''")
		field47c = replace(request.form("field47c"), "'", "''")
	field48a = replace(request.form("field48a"), "'", "''")
	field48b = replace(request.form("field48b"), "'", "''")
	field48c = replace(request.form("field48c"), "'", "''")
	field48d = replace(request.form("field48d"), "'", "''")
	field48e = replace(request.form("field48e"), "'", "''")
	field48f = replace(request.form("field48f"), "'", "''")
		field49a = replace(request.form("field49a"), "'", "''")
		field49b = replace(request.form("field49b"), "'", "''")
		field49c = replace(request.form("field49c"), "'", "''")
	field50a = replace(request.form("field50a"), "'", "''")
	field50b = replace(request.form("field50b"), "'", "''")
	field50c = replace(request.form("field50c"), "'", "''")
	field50d = replace(request.form("field50d"), "'", "''")
		field51a = replace(request.form("field51a"), "'", "''")
		field51b = replace(request.form("field51b"), "'", "''")
		field51c = replace(request.form("field51c"), "'", "''")
	field52a = replace(request.form("field52a"), "'", "''")
	field52b = replace(request.form("field52b"), "'", "''")
	field52c = replace(request.form("field52c"), "'", "''")
		field53a = replace(request.form("field53a"), "'", "''")
		field53b = replace(request.form("field53b"), "'", "''")
		field53c = replace(request.form("field53c"), "'", "''")
	field54a = replace(request.form("field54a"), "'", "''")
	field54b = replace(request.form("field54b"), "'", "''")
	field54c = replace(request.form("field54c"), "'", "''")
		field55a = replace(request.form("field55a"), "'", "''")
		field55b = replace(request.form("field55b"), "'", "''")
	field56a = replace(request.form("field56a"), "'", "''")
	field56b = replace(request.form("field56b"), "'", "''")
	field56c = replace(request.form("field56c"), "'", "''")
	field56d = replace(request.form("field56d"), "'", "''")
	field56e = replace(request.form("field56e"), "'", "''")
	field56f = replace(request.form("field56f"), "'", "''")
		field57a = replace(request.form("field57a"), "'", "''")
		field57b = replace(request.form("field57b"), "'", "''")
		field57c = replace(request.form("field57c"), "'", "''")
		field57d = replace(request.form("field57d"), "'", "''")
	field58a = replace(request.form("field58a"), "'", "''")
	field58b = replace(request.form("field58b"), "'", "''")
	field58c = replace(request.form("field58c"), "'", "''")
	field58d = replace(request.form("field58d"), "'", "''")
		field59a = replace(request.form("field59a"), "'", "''")
		field59b = replace(request.form("field59b"), "'", "''")
		field59c = replace(request.form("field59c"), "'", "''")
		field59d = replace(request.form("field59d"), "'", "''")
		field59e = replace(request.form("field59e"), "'", "''")
		field59f = replace(request.form("field59f"), "'", "''")
		field59g = replace(request.form("field59g"), "'", "''")
		field59h = replace(request.form("field59h"), "'", "''")
	field59a1 = replace(request.form("field59a1"), "'", "''")
		field60a = replace(request.form("field60a"), "'", "''")
		field60a1 = replace(request.form("field60a1"), "'", "''")
		field60a2 = replace(request.form("field60a2"), "'", "''")
		field60b = replace(request.form("field60b"), "'", "''")
		field60b1 = replace(request.form("field60b1"), "'", "''")
		field60c = replace(request.form("field60c"), "'", "''")
	field61a = replace(request.form("field61a"), "'", "''")
	field61a1 = replace(request.form("field61a1"), "'", "''")
	field61a2 = replace(request.form("field61a2"), "'", "''")
	field61b = replace(request.form("field61b"), "'", "''")
	field61b1 = replace(request.form("field61b1"), "'", "''")
	field61c = replace(request.form("field61c"), "'", "''")
	field61c1 = replace(request.form("field61c1"), "'", "''")
	field61c2 = replace(request.form("field61c2"), "'", "''")
	field61d = replace(request.form("field61d"), "'", "''")
		field62a = replace(request.form("field62a"), "'", "''")
		field62b = replace(request.form("field62b"), "'", "''")
		field62c = replace(request.form("field62c"), "'", "''")
		field62d = replace(request.form("field62d"), "'", "''")
		field62e = replace(request.form("field62e"), "'", "''")
	field63a = replace(request.form("field63a"), "'", "''")
	field63b = replace(request.form("field63b"), "'", "''")
	field63c = replace(request.form("field63c"), "'", "''")
	field63d = replace(request.form("field63d"), "'", "''")
		field64a = replace(request.form("field64a"), "'", "''")
		field64a1 = replace(request.form("field64a1"), "'", "''")
		field64b = replace(request.form("field64b"), "'", "''")
		field64c = replace(request.form("field64c"), "'", "''")
		field64d = replace(request.form("field64d"), "'", "''")
	field65a = replace(request.form("field65a"), "'", "''")
	field65b = replace(request.form("field65b"), "'", "''")
	field65c = replace(request.form("field65c"), "'", "''")
	field65d = replace(request.form("field65d"), "'", "''")
	field65e = replace(request.form("field65e"), "'", "''")
	field65f = replace(request.form("field65f"), "'", "''")
		field66a = replace(request.form("field66a"), "'", "''")
		field66b = replace(request.form("field66b"), "'", "''")
		field66c = replace(request.form("field66c"), "'", "''")
		field66d = replace(request.form("field66d"), "'", "''")
		field66e = replace(request.form("field66e"), "'", "''")
	field67a = replace(request.form("field67a"), "'", "''")
	field67b = replace(request.form("field67b"), "'", "''")
	field67c = replace(request.form("field67c"), "'", "''")
		field68a = replace(request.form("field68a"), "'", "''")
		field68b = replace(request.form("field68b"), "'", "''")
		field68c = replace(request.form("field68c"), "'", "''")
		field68d = replace(request.form("field68d"), "'", "''")
	field69a = replace(request.form("field69a"), "'", "''")
	field69b = replace(request.form("field69b"), "'", "''")
	field69c = replace(request.form("field69c"), "'", "''")
	field69d = replace(request.form("field69d"), "'", "''")
		field70a = replace(request.form("field70a"), "'", "''")
		field70b = replace(request.form("field70b"), "'", "''")
		field70c = replace(request.form("field70c"), "'", "''")
		field70d = replace(request.form("field70d"), "'", "''")
		field70e = replace(request.form("field70e"), "'", "''")
	field71a = replace(request.form("field71a"), "'", "''")
	field71b = replace(request.form("field71b"), "'", "''")
	field71c = replace(request.form("field71c"), "'", "''")
	field71d = replace(request.form("field71d"), "'", "''")
		field72a = replace(request.form("field72a"), "'", "''")
		field72b = replace(request.form("field72b"), "'", "''")
		field72c = replace(request.form("field72c"), "'", "''")
		field72d = replace(request.form("field72d"), "'", "''")
	field73a = replace(request.form("field73a"), "'", "''")
	field73b = replace(request.form("field73b"), "'", "''")
	field73c = replace(request.form("field73c"), "'", "''")
	field73d = replace(request.form("field73d"), "'", "''")
	field73e = replace(request.form("field73e"), "'", "''")
	field73f = replace(request.form("field73f"), "'", "''")
		field74a = replace(request.form("field74a"), "'", "''")
		field74b = replace(request.form("field74b"), "'", "''")
		field74c = replace(request.form("field74c"), "'", "''")
		field74d = replace(request.form("field74d"), "'", "''")
		field74e = replace(request.form("field74e"), "'", "''")
		field74f = replace(request.form("field74f"), "'", "''")
	field75a = replace(request.form("field75a"), "'", "''")
	field75b = replace(request.form("field75b"), "'", "''")
	field75c = replace(request.form("field75c"), "'", "''")
	field75d = replace(request.form("field75d"), "'", "''")
		field76a = replace(request.form("field76a"), "'", "''")
		field76a1 = replace(request.form("field76a1"), "'", "''")
		field76b = replace(request.form("field76b"), "'", "''")
		field76b1 = replace(request.form("field76b1"), "'", "''")
		field76c = replace(request.form("field76c"), "'", "''")
		field76c1 = replace(request.form("field76c1"), "'", "''")
		field76d = replace(request.form("field76d"), "'", "''")
		field76d1 = replace(request.form("field76d1"), "'", "''")
		field76e = replace(request.form("field76e"), "'", "''")
		field76e1 = replace(request.form("field76e1"), "'", "''")
		field76f = replace(request.form("field76f"), "'", "''")
		field76f1 = replace(request.form("field76f1"), "'", "''")
		field76g = replace(request.form("field76g"), "'", "''")
		field76g1 = replace(request.form("field76g1"), "'", "''")
	field77a = replace(request.form("field77a"), "'", "''")
	field77b = replace(request.form("field77b"), "'", "''")
	field77c = replace(request.form("field77c"), "'", "''")
	field77d = replace(request.form("field77d"), "'", "''")
	field77e = replace(request.form("field77e"), "'", "''")
	field77f = replace(request.form("field77f"), "'", "''")
	field77g = replace(request.form("field77g"), "'", "''")
	field77g1 = replace(request.form("field77g1"), "'", "''")
		field78a = replace(request.form("field78a"), "'", "''")
		field78b = replace(request.form("field78b"), "'", "''")
		field78c = replace(request.form("field78c"), "'", "''")
		field78d = replace(request.form("field78d"), "'", "''")
		field78e = replace(request.form("field78e"), "'", "''")
		field78f = replace(request.form("field78f"), "'", "''")
		field78g = replace(request.form("field78g"), "'", "''")
		field78g1 = replace(request.form("field77g1"), "'", "''")
	field79a = replace(request.form("field79a"), "'", "''")
	field79a1 = replace(request.form("field79a1"), "'", "''")
	field79a2 = replace(request.form("field79a2"), "'", "''")
	field79a3 = replace(request.form("field79a3"), "'", "''")
	field79a4 = replace(request.form("field79a4"), "'", "''")
	field79b = replace(request.form("field79b"), "'", "''")
	field79b1 = replace(request.form("field79b1"), "'", "''")
	field79b2 = replace(request.form("field79b2"), "'", "''")
	field79b3 = replace(request.form("field79b3"), "'", "''")
	field79b4 = replace(request.form("field79b4"), "'", "''")
	field79c = replace(request.form("field79c"), "'", "''")
	field79c1 = replace(request.form("field79c1"), "'", "''")
	field79c2 = replace(request.form("field79c2"), "'", "''")
	field79c3 = replace(request.form("field79c3"), "'", "''")
	field79c4 = replace(request.form("field79c4"), "'", "''")
	field79d = replace(request.form("field79d"), "'", "''")
	field79d1 = replace(request.form("field79d1"), "'", "''")
	field79d2 = replace(request.form("field79d2"), "'", "''")
	field79d3 = replace(request.form("field79d3"), "'", "''")
	field79d4 = replace(request.form("field79d4"), "'", "''")
	field79e = replace(request.form("field79e"), "'", "''")
	field79e1 = replace(request.form("field79e1"), "'", "''")
	field79e2 = replace(request.form("field79e2"), "'", "''")
	field79e3 = replace(request.form("field79e3"), "'", "''")
	field79e4 = replace(request.form("field79e4"), "'", "''")
	field79f = replace(request.form("field79f"), "'", "''")
	field79f1 = replace(request.form("field79f1"), "'", "''")
	field79f2 = replace(request.form("field79f2"), "'", "''")
	field79f3 = replace(request.form("field79f3"), "'", "''")
	field79f4 = replace(request.form("field79f4"), "'", "''")
		field80a = replace(request.form("field80a"), "'", "''")
		field80b = replace(request.form("field80b"), "'", "''")
		field80c = replace(request.form("field80c"), "'", "''")
	field81a = replace(request.form("field81a"), "'", "''")
	field81b = replace(request.form("field81b"), "'", "''")
	field81c = replace(request.form("field81c"), "'", "''")
		field82a = replace(request.form("field82a"), "'", "''")
		field82b = replace(request.form("field82b"), "'", "''")
		field82c = replace(request.form("field82c"), "'", "''")
	field83a = replace(request.form("field83a"), "'", "''")
	field83b = replace(request.form("field83b"), "'", "''")
	field83c = replace(request.form("field83c"), "'", "''")
		field84a = replace(request.form("field84a"), "'", "''")
		field84b = replace(request.form("field84b"), "'", "''")
		field84c = replace(request.form("field84c"), "'", "''")
	field85a = replace(request.form("field85a"), "'", "''")
	field85b = replace(request.form("field85b"), "'", "''")
	field85c = replace(request.form("field85c"), "'", "''")
		field86a = replace(request.form("field86a"), "'", "''")
		field86b = replace(request.form("field86b"), "'", "''")
		field86c = replace(request.form("field86c"), "'", "''")
	field87a = replace(request.form("field87a"), "'", "''")
	field87a1 = replace(request.form("field87a1"), "'", "''")
	field87b = replace(request.form("field87b"), "'", "''")
	field87c = replace(request.form("field87c"), "'", "''")
		field88a = replace(request.form("field88a"), "'", "''")
		field88b = replace(request.form("field88b"), "'", "''")
		field88c = replace(request.form("field88c"), "'", "''")
	field89a = replace(request.form("field89a"), "'", "''")
	field89b = replace(request.form("field89b"), "'", "''")
	field89c = replace(request.form("field89c"), "'", "''")
		field90a = replace(request.form("field90a"), "'", "''")
		field90b = replace(request.form("field90b"), "'", "''")
		field90c = replace(request.form("field90c"), "'", "''")
	field91a = replace(request.form("field91a"), "'", "''")
	field91b = replace(request.form("field91b"), "'", "''")
	field91c = replace(request.form("field91c"), "'", "''")
		field92a = replace(request.form("field92a"), "'", "''")
		field92b = replace(request.form("field92b"), "'", "''")
		field92c = replace(request.form("field92c"), "'", "''")
	field93a = replace(request.form("field93a"), "'", "''")
	field93b = replace(request.form("field93b"), "'", "''")
	field93c = replace(request.form("field93c"), "'", "''")
		field94a = replace(request.form("field94a"), "'", "''")
		field94b = replace(request.form("field94b"), "'", "''")
		field94c = replace(request.form("field94c"), "'", "''")
	field95a = replace(request.form("field95a"), "'", "''")
	field95b = replace(request.form("field95b"), "'", "''")
	field95c = replace(request.form("field95c"), "'", "''")
		field96a = replace(request.form("field96a"), "'", "''")
		field96b = replace(request.form("field96b"), "'", "''")
		field96c = replace(request.form("field96c"), "'", "''")
	field97a = replace(request.form("field97a"), "'", "''")
	field97b = replace(request.form("field97b"), "'", "''")
	field97c = replace(request.form("field97c"), "'", "''")
		field98a = replace(request.form("field98a"), "'", "''")
		field98b = replace(request.form("field98b"), "'", "''")
		field98c = replace(request.form("field98c"), "'", "''")
	field99a = replace(request.form("field99a"), "'", "''")
	field99b = replace(request.form("field99b"), "'", "''")
	field99c = replace(request.form("field99c"), "'", "''")
		field100a = replace(request.form("field100a"), "'", "''")
		field100b = replace(request.form("field100b"), "'", "''")
		field100c = replace(request.form("field100c"), "'", "''")
	field101a = replace(request.form("field101a"), "'", "''")
	field101b = replace(request.form("field101b"), "'", "''")
	field101c = replace(request.form("field101c"), "'", "''")
		field102a = replace(request.form("field102a"), "'", "''")
		field102b = replace(request.form("field102b"), "'", "''")
		field102c = replace(request.form("field102c"), "'", "''")
	field103a = replace(request.form("field103a"), "'", "''")
	field103b = replace(request.form("field103b"), "'", "''")
	field103c = replace(request.form("field103c"), "'", "''")
		field104a = replace(request.form("field104a"), "'", "''")
		field104b = replace(request.form("field104b"), "'", "''")
		field104c = replace(request.form("field1040c"), "'", "''")
	field105a = replace(request.form("field105a"), "'", "''")
	field105b = replace(request.form("field105b"), "'", "''")
	field105c = replace(request.form("field105c"), "'", "''")
		field106a = replace(request.form("field106a"), "'", "''")
		field106b = replace(request.form("field106b"), "'", "''")
		field106c = replace(request.form("field106c"), "'", "''")
	field107a = replace(request.form("field107a"), "'", "''")
	field107b = replace(request.form("field107b"), "'", "''")
	field107c = replace(request.form("field107c"), "'", "''")
		field108a = replace(request.form("field108a"), "'", "''")
		field108b = replace(request.form("field108b"), "'", "''")
		field108c = replace(request.form("field108c"), "'", "''")
	field109a = replace(request.form("field109a"), "'", "''")
	field109b = replace(request.form("field109b"), "'", "''")
	field109c = replace(request.form("field109c"), "'", "''")
	
	SQL = "UPDATE tblanswersa SET" &_ 
	"  Question1='" & fielda & "'" &_
	", Question2='" & fieldb & "'" &_
	", Question3='" & fieldc & "'" &_
	", Question4='" & fieldd & "'" &_
	", Question5='" & fielde & "'" &_
	", Question6='" & fieldf & "'" &_
	", Question6a='" & fieldf1 & "'" &_
	", Question7='" & fieldg & "'" &_
	", Question8='" & fieldh & "'" &_
	", Question9='" & fieldi & "'" &_
	", Question10='" & fieldj & "'" &_
	", Question11='" & fieldk & "'" &_
	", Question12='" & fieldl & "'" &_
	", Question13='" & fieldm & "'" &_
	", Question14='" & fieldn & "'" &_
	", Question15='" & fieldo & "'" &_
	", Question16='" & fieldp & "'" &_
	", Question17='" & fieldq & "'" &_
	", Question17a='" & fieldq1 & "'" &_
	", Question18='" & fieldr & "'" &_
	", Question19='" & fieldt & "'" &_
	", Question20='" & fieldu & "'" &_
		", Question21a='" & field1a & "'" &_
		", Question21b='" & field1b & "'" &_
		", Question21c='" & field1c & "'" &_
		", Question21d='" & field1d & "'" &_
		", Question21e='" & field1e & "'" &_
	", Question22a='" & field2a & "'" &_
	", Question22b='" & field2b & "'" &_
		", Question23a='" & field3a & "'" &_
		", Question23b='" & field3b & "'" &_
		", Question23b1='" & field3b1 & "'" &_
		", Question23c='" & field3c & "'" &_
		", Question23c1='" & field3c1 & "'" &_
		", Question23d='" & field3d & "'" &_
		", Question23d1='" & field3d1 & "'" &_
		", Question23d2='" & field3d2 & "'" &_
		", Question23e='" & field3e & "'" &_
	", Question24a='" & field4a & "'" &_
	", Question24b='" & field4b & "'" &_
	", Question24c='" & field4c & "'" &_
	", Question24d='" & field4d & "'" &_
	", Question24e='" & field4e & "'" &_
		", Question25a='" & field5a & "'" &_
		", Question25a1='" & field5a1 & "'" &_
		", Question25a2='" & field5a2 & "'" &_
		", Question25b='" & field5b & "'" &_
		", Question25c='" & field5c & "'" &_
	", Question26a='" & field6a & "'" &_
	", Question26b='" & field6b & "'" &_
	", Question26c='" & field6c & "'" &_
		", Question27a='" & field7a & "'" &_
		", Question27b='" & field7b & "'" &_
		", Question27c='" & field7c & "'" &_
	", Question28a='" & field8a & "'" &_
	", Question28a1='" & field8a1 & "'" &_
	", Question28a2='" & field8a2 & "'" &_
	", Question28a3='" & field8a3 & "'" &_
	", Question28a4='" & field8a4 & "'" &_
	", Question28a5='" & field8a5 & "'" &_
	", Question28a6='" & field8a6 & "'" &_
	", Question28a7='" & field8a7 & "'" &_
	", Question28a8='" & field8a8 & "'" &_
	", Question28b='" & field8b & "'" &_
	", Question28b1='" & field8b1 & "'" &_
	", Question28b2='" & field8b2 & "'" &_
	", Question28c='" & field8c & "'" &_
	", Question28d='" & field8d & "'" &_
		", Question29a='" & field9a & "'" &_
		", Question29b='" & field9b & "'" &_
		", Question29b1='" & field9b1 & "'" &_
		", Question29b2='" & field9b2 & "'" &_
		", Question29c='" & field9c & "'" &_
		", Question29c1='" & field9c1 & "'" &_
		", Question29c2='" & field9c2 & "'" &_
		", Question29c3='" & field9c3 & "'" &_
		", Question29c4='" & field9c4 & "'" &_
		", Question29d='" & field9d & "'" &_
		", Question29d1='" & field9d1 & "'" &_
		", Question29d2='" & field9d2 & "'" &_
		", Question29d3='" & field9d3 & "'" &_
		", Question29d4='" & field9d4 & "'" &_
		", Question29e='" & field9e & "'" &_
		", Question29e1='" & field9e1 & "'" &_
		", Question29e2='" & field9e2 & "'" &_
		", Question29e3='" & field9e3 & "'" &_
		", Question29f='" & field9f & "'" &_
		", Question29f1='" & field9f1 & "'" &_
		", Question29f2='" & field9f2 & "'" &_
		", Question29f3='" & field9f3 & "'" &_
		", Question29f4='" & field9f4 & "'" &_
	", Question30a='" & field10a & "'" &_
	", Question30b='" & field10b & "'" &_
	", Question30c='" & field10c & "'" &_
	", Question30d='" & field10d & "'" &_
		", Question31a='" & field11a & "'" &_
		", Question31a1='" & field11a1 & "'" &_
		", Question31a2='" & field11a2 & "'" &_
		", Question31b='" & field11b & "'" &_
		", Question31c='" & field11c & "'" &_
	", Question32a='" & field22a & "'" &_
	", Question32b='" & field22b & "'" &_
	", Question32c='" & field22c & "'" &_
	", Question32d='" & field22d & "'" &_
	", Question32e='" & field22e & "'" &_
	", Question32f='" & field22f & "'" &_
	", Question32g='" & field22g & "'" &_
		", Question33a='" & field13a & "'" &_
		", Question33b='" & field13b & "'" &_
		", Question33c='" & field13c & "'" &_
		", Question33d='" & field13d & "'" &_
	", Question34a='" & field14a & "'" &_
	", Question34b='" & field14b & "'" &_
	", Question34c='" & field14c & "'" &_
	", Question34d='" & field14d & "'" &_
		", Question35a='" & field15a & "'" &_
		", Question35b='" & field15b & "'" &_
		", Question35c='" & field15c & "'" &_
		", Question35d='" & field15d & "'" &_
		", Question35e='" & field15e & "'" &_
		", Question35f='" & field15f & "'" &_
	", Question36a='" & field16a & "'" &_
	", Question36b='" & field16b & "'" &_
	", Question36c='" & field16c & "'" &_
	", Question36d='" & field16d & "'" &_
	", Question36e='" & field16e & "'" &_
	", Question36f='" & field16f & "'" &_
		", Question37a='" & field17a & "'" &_
		", Question37b='" & field17b & "'" &_
		", Question37c='" & field17c & "'" &_
	", Question38a='" & field18a & "'" &_
	", Question38b='" & field18b & "'" &_
	", Question38c='" & field18c & "'" &_
	", Question38d='" & field18d & "'" &_
	", Question38e='" & field18e & "'" &_
		", Question39a='" & field19a & "'" &_
		", Question39b='" & field19b & "'" &_
		", Question39c='" & field19c & "'" &_
		", Question39d='" & field19d & "'" &_
		", Question39d1='" & field19d1 & "'" &_
		", Question39d2='" & field19d2 & "'" &_
		", Question39d3='" & field19d3 & "'" &_
		", Question39e='" & field19e & "'" &_
	", Question40a='" & field20a & "'" &_
	", Question40b='" & field20b & "'" &_
	", Question40c='" & field20c & "'" &_
	", Question40d='" & field20d & "'" &_
	", Question40e='" & field20e & "'" &_
	", Question40f='" & field20f & "'" &_
	", Question40g='" & field20g & "'" &_
		", Question41a='" & field21a & "'" &_
		", Question41b='" & field21b & "'" &_
	", Question42a='" & field22a & "'" &_
	", Question42b='" & field22b & "'" &_
		", Question43a='" & field23a & "'" &_
		", Question43b='" & field23b & "'" &_
	", Question44a='" & field24a & "'" &_
	", Question44b='" & field24b & "'" &_
	", Question44c='" & field24c & "'" &_
		", Question45a='" & field25a & "'" &_
		", Question45b='" & field25b & "'" &_
		", Question45c='" & field25c & "'" &_
	", Question46a='" & field26a & "'" &_
	", Question46b='" & field26b & "'" &_
	", Question46c='" & field26c & "'" &_
	", Question46c1='" & field26c1 & "'" &_
	", Question46d='" & field26d & "'" &_
	", Question46d1='" & field26d1 & "'" &_
	", Question46e='" & field26e & "'" &_
		", Question47a='" & field27a & "'" &_
		", Question47b='" & field27b & "'" &_
		", Question47c='" & field27c & "'" &_
	", Question48a='" & field28a & "'" &_
	", Question48b='" & field28b & "'" &_
	", Question48c='" & field28c & "'" &_
		", Question49a='" & field29a & "'" &_
		", Question49b='" & field29b & "'" &_
		", Question49c='" & field29c & "'" &_
		", Question49d='" & field29d & "'" &_
	", Question50a='" & field30a & "'" &_
	", Question50b='" & field30b & "'" &_
	", Question50c='" & field30c & "'" &_
	", Question50d='" & field30d & "'" &_
	", Question50e='" & field30e & "'" &_
	", Question50e1='" & field30e1 & "'" &_
	", Question50e2='" & field30e2 & "'" &_
	", Question50e3='" & field30e3 & "'" &_
		", Question51a='" & field21a & "'" &_
		", Question51b='" & field21b & "'" &_
		", Question51c='" & field21c & "'" &_
	", Question52a='" & field22a & "'" &_
	", Question52b='" & field22b & "'" &_
	", Question52c='" & field22c & "'" &_
	", Question52d='" & field22d & "'" &_
		", Question53a='" & field33a & "'" &_
		", Question53b='" & field33b & "'" &_
		", Question53c='" & field33c & "'" &_
		", Question53d='" & field33d & "'" &_
	", Question54a='" & field34a & "'" &_
	", Question54b='" & field34b & "'" &_
		", Question55a='" & field35a & "'" &_
		", Question55b='" & field35b & "'" &_
		", Question55c='" & field35c & "'" &_
		", Question55d='" & field35d & "'" &_
		", Question55e='" & field35e & "'" &_
		", Question55f='" & field35f & "'" &_
		", Question55f1='" & field35f1 & "'" &_
		", Question55g='" & field35g & "'" &_
		", Question55g1='" & field35g1 & "'" &_
		", Question55h='" & field35h & "'" &_
	", Question56a='" & field36a & "'" &_
	", Question56b='" & field36b & "'" &_
		", Question57a='" & field37a & "'" &_
		", Question57b='" & field37b & "'" &_
		", Question57c='" & field37c & "'" &_
	", Question58a='" & field38a & "'" &_
	", Question58b='" & field38b & "'" &_
		", Question59a='" & field39a & "'" &_
		", Question59b='" & field39b & "'" &_
		", Question59c='" & field39c & "'" &_
		", Question59d='" & field39d & "'" &_
	", Question60a='" & field40a & "'" &_
	", Question60b='" & field40b & "'" &_
	", Question60c='" & field40c & "'" &_
		", Question61a='" & field41a & "'" &_
		", Question61b='" & field41b & "'" &_
		", Question61c='" & field41c & "'" &_
	", Question62a='" & field42a & "'" &_
	", Question62b='" & field42b & "'" &_
		", Question63a='" & field43a & "'" &_
		", Question63b='" & field43b & "'" &_
		", Question63c='" & field43c & "'" &_
	", Question64a='" & field44a & "'" &_
	", Question64b='" & field44b & "'" &_
	", Question64c='" & field44c & "'" &_
		", Question65a='" & field45a & "'" &_
		", Question65b='" & field45b & "'" &_
		", Question65c='" & field45c & "'" &_
 	" WHERE KeyID='" & KeyID & "'"
	rs = gobjConnection.Execute(SQL)
	
	response.redirect("step3.html?KeyID=" & KeyID)

%>